# Generated by Django 6.1 on 2026-09-03 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price_unit',
            field=models.CharField(choices=[('day', 'per day'), ('week', 'per week'), ('month', 'per month')], default='day', max_length=10),
        ),
    ]
