# Generated by Django 6.1 on 2026-08-29 09:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_status',
            field=models.CharField(choices=[('unverified', 'Not verified'), ('pending', 'Pending review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='unverified', max_length=12),
        ),
        migrations.CreateModel(
            name='OwnerVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_legal_name', models.CharField(help_text='Full name exactly as it appears on the National ID.', max_length=150)),
                ('nin', models.CharField(help_text='11-digit National Identification Number.', max_length=11, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'Enter the 11-digit NIN exactly as issued.')])),
                ('selfie_image', models.ImageField(help_text='A live selfie taken during submission, for a reviewer to compare against the NIN.', upload_to='verifications/selfies/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, help_text='Shown to the item owner if the submission is rejected.', max_length=255)),
                ('owner', models.OneToOneField(limit_choices_to={'role': 'item_owner'}, on_delete=django.db.models.deletion.CASCADE, related_name='verification', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Owner verification',
                'verbose_name_plural': 'Owner verifications',
            },
        ),
    ]
