# Generated by Django 6.1 on 2026-08-29 22:44

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_verification_status_ownerverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerverification',
            name='nin_back_image',
            field=models.ImageField(blank=True, help_text="Back photograph of the owner's physical NIN card.", upload_to='verifications/nin-cards/back/', validators=[accounts.models.validate_verification_image_size]),
        ),
        migrations.AddField(
            model_name='ownerverification',
            name='nin_front_image',
            field=models.ImageField(blank=True, help_text="Front photograph of the owner's physical NIN card.", upload_to='verifications/nin-cards/front/', validators=[accounts.models.validate_verification_image_size]),
        ),
        migrations.AlterField(
            model_name='ownerverification',
            name='selfie_image',
            field=models.ImageField(blank=True, help_text='A live selfie taken during submission, for a reviewer to compare against the NIN.', upload_to='verifications/selfies/', validators=[accounts.models.validate_verification_image_size]),
        ),
    ]
