# Generated by Django 6.1 on 2026-08-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Direct phone number for pickup/delivery coordination.', max_length=30),
        ),
        migrations.AddField(
            model_name='transaction',
            name='delivery_address',
            field=models.CharField(blank=True, help_text='Customer delivery address or area.', max_length=255),
        ),
        migrations.AddField(
            model_name='transaction',
            name='delivery_option',
            field=models.CharField(choices=[('pickup', 'Self-Pickup at Owner Location'), ('delivery', 'Direct Delivery to Customer Address')], default='pickup', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='pickup_notes',
            field=models.TextField(blank=True, help_text='Special instructions, pickup time, or handover details.'),
        ),
    ]
